import mongoose from "mongoose";
const Schema = mongoose.Schema;

const gupshupApiKey =
  process.env.mode !== "production"
    ? "0bb84ddf52e94f33cf02a70d3b41438a"
    : "53da81aca484415bc152fa723801de88";
const appName = process.env.mode !== "production" ? "ShelleySchool" : "AiSensy";

// Create Schema
const AssistantSchema = new Schema(
  {
    assistantName: {
      type: String,
      unique: true,
      required: true,
    },
    clientId: {
      type: String,
      required: true,
    },
    whatsappNumber: {
      type: String,
    },
    appName: {
      type: String,
      default: appName,
    },
    gupshupApiKey: {
      type: String,
      default: gupshupApiKey,
    },
    testNumber: {
      type: String,
    },
    testName: {
      type: String,
    },
    testCountryCode: {
      type: String,
    },
    dfProjectId: "",
    sessionKey: {
      type: Object,
    },
    campaignReportingAllowed: {
      type: Boolean,
      default: false,
    },
    keyLastUpdated: {
      type: Date,
      default: null,
    },
    wabaAppStatus: {
      type: Object,
      default: {},
    },
    activePlan: { type: String },
    planActivatedOn: { type: Date },
    excessUsage: { type: Number },
    remainingSessionMessages: { type: Number },
    remainingEnterpriseSessions: { type: Number },
    templateCredit: { type: Number },
    partnerWhatsappCredit: { type: Number },
    remainingCredit: { type: Number },
    selectedMetaUserId: String,
    selectedMetaBusinessId: String,
    selectedMetaCatalogueId: String,
    selectedMetaBusinessAccessToken: String,
    orders: [],
    billingAddress: { type: Object },
    verificationDetails: { type: Object },
    isWhatsappVerified: { type: Boolean, default: false },
    maxAgents: { type: Number, default: 15 },
    attributes: [
      {
        action: String,
        name: String,
      },
    ],
    API_CODE: String,
    type: { type: String },
    status: {
      type: String,
      enum: [
        "active",
        "unpaid",
        "terminated",
        "pending",
        "suspended",
        "stopped",
        "archived",
      ],
      default: "active",
    },
    dialogflowType: { type: String, default: "t1" },
    defaultCurrency: String,
    country: String,
    templateTier: {
      type: String,
      default: "Tier 1",
    },
    dailyTemplateLimit: Number,
    webhooks: {
      type: Object,
    },
    autoResolve: {
      type: Boolean,
      default: true,
    },
    apiKey360: String,
    providerType: String,
    gupshupAppId: String,
    gupshupAppToken: String,
    subscriptionId: {
      type: String,
    },
    remainingMac: Number, // Excess and Remaining MAC is deprecated but is kept here for monitering cache.
    excessMac: Number, //                                  "
    macUsage: Number,
    unbilledMac: Number,
    cardAdded: String,
    macQuota: Number,
    subscriptionStatus: {
      type: String,
      enum: ["active", "cancelled", "scheduled downgrade"],
    },
    appliedForWaba: Boolean,
    ongoingBillingProcess: Object,
    subscriptionScheduled: Object,
    promotionalCredits: Number,
    currency: String,
    timezone: { type: String, default: "Asia/Calcutta GMT+05:30" },
    isEcom: Boolean,
    leadSquaredWebhookUrl: String,
    webEngageWebhookUrl: Object,
    WebengageEventId: String,
    WebengageEventKey: String,
    moEngageWebhookUrl: String,
    webEngageKey: Object,
    WEB_KEY: String,
    MO_KEY: String,
    deliveryCallbackURL: String,
    inboundMessageURL: String,
    CleverTapkey: String,
    subscriptionStartedWith: String,
    planRenewalOn: Date,
    d360ChannelId: String,
    fbManagerVerified: String,
    displayNameVerified: String,
    whatsAppDisplayName: String,
    whatsAppDisplayImage: String,
    whatsAppAbout: String,
    whatsAppBusinessProfile: Object,
    profileSetupDone: Boolean,
    appliedForGreenTick: Boolean,
    qualityRating: String,
    branding: {
      type: Boolean,
      default: true,
    },
    allowPurchase: {
      type: Boolean,
      default: true,
    },
    subscriptionStartedOn: Date,
    firstPaidPlanName: String,
    firstPaidPlanStartedOn: Date,
    partnerId: String,
    partnerChannelId: String,
    tagLimit: Number,
    attributeLimit: Number,
    wabaPin: String,
    wabaAppId: String,
    wabaNumberId: String,
    wabaAccessToken: String,
    templateNamespace: String,
    chargebeePlan: Boolean,
    wabaProgressStep: Number,
    displayNameRejectionReason: String,
    freeTierCoversationCount: { type: Number },
    wabaActivatedOn: Date,
    selectedMetaPageId: String,
    selectedMetaAdAccountId: String,
    freezedMetaPageId: String,
    freezedMetaAdAccountId: String,
    fbUserId: String,
    fbGrantedScopes: String,
    fbConnected: Boolean,
    fbConnectedBy: String,
    fbUserToken: String,
    metaAdsDetails: Object,
    allowCTW: Boolean,
    optSetting: Object,
    skipApiCampaign: { type: Boolean, default: true },
    partnerArchived: { type: Boolean, default: false },
    campaignAnalyticsEnabled: Boolean,
    campaignSchedulingEnabled: Boolean,
    clickTrackingEnabled: Boolean,
    filterFreezeEnabled: Boolean,
    metaAdvanceTargetingEnabled: Boolean,
    planTier: String,
    planDuration: Number,
    directApikey: String,
    directApiWebookUrl: String,
    planStoppedOn: Date,
    familyId: String,
    apiFormDetails: Object,
    autoWccRecharge: Object,
    ecomAppStore: String,
    chatSearchEnabled: Boolean,
    disableEcomm: Boolean,
    fbBusinessId: String,
    customerId: String,
    placeOfSupply: String,
    ongoingPlanBillingProcess: Object,
    wabaActivated: Boolean,
    apiLimit: Number,
    flowConfiguration: Object,
    minAllowedBalance: Number,
    aggCreditRecharged: Number,
    aggCreditUsage: Number,
    addons: {
      type: Object,
      default: {},
    },
    referralId: String,
    wabaTpt: String,
    wabaStatusTpt: String,
    planManagement: String,
    referralShortLink: String,
    embeddedSignupUrl: String,
    razorpaylink: String,
    paymentLinkId: String,
    orderCheckoutDetails: Object,
    aggConversationCount: Object,
    subsrazorpayLink: String,
    subspaymentLinkId: String,
    numberBuyStep: Number,
    csvScheduleEnabled: Boolean,
    optReportingEnabled: { type: Boolean, default: false },
    cleverTapOptField: { type: Boolean, default: false },
    isOrderFlowEnabled: { type: Boolean, default: false },
    moEngageOptField: { type: Boolean, default: false },
    webEngageOptField: { type: Boolean, default: false },
    isCatalogueVisibleOnBusiness: { type: Boolean, default: false },
    temporarySubs: { type: Object },
    contactPerson: { type: String },
    isoCode: String,
    metaAdsCredit: { type: Number },
    paymentPlanId: String,
    affiliateId: String,
  },
  { timestamps: true }
);

const Assistant = mongoose.model("assistant", AssistantSchema);

export default Assistant;
